### ISSUE TITLE
Invalid face weight 

### ISSUE THREAD

**Issue by BonfaceKilz** [idlip/haki#1]
Hi.  

I'm currently running: GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)

I tried loading this theme using:

```elisp
(use-package haki-theme :ensure t)
(load-theme 'haki t)
```

I am un-able to load this theme.  When I "M-x toggle-debug-on-error", I get the following stack-trace:

```
Debugger entered--Lisp error: (error "Invalid face weight" heavy)
  set-face-attribute(avy-lead-face #<frame *scratch* 0x888bcf8> :weight heavy :foreground "#FFFFFF" :background "#2e8b6d")
  face-spec-set-2(avy-lead-face #<frame *scratch* 0x888bcf8> (:weight heavy :foreground "#FFFFFF" :background "#2e8b6d"))
  face-spec-recalc(avy-lead-face #<frame *scratch* 0x888bcf8>)
  custom-theme-recalc-face(avy-lead-face)
  enable-theme(haki)
  load-theme(haki nil nil)
  funcall-interactively(load-theme haki nil nil)
  command-execute(load-theme record)
  execute-extended-command(nil "load-theme" nil)
  funcall-interactively(execute-extended-command nil "load-theme" nil)
  command-execute(execute-extended-command)
```

There's also:

```
face-spec-set-2: Invalid face weight: demi-bold
```

Is there a require somewhere that's missing?  Or a dependency that I'm missing?

**Comment by idlip** [comment]
That's weird I cannot see this error even on the web for emacs. 

> ‘:weight’                                                                                                              
>                                                                                                                       
> VALUE specifies the weight of the font to use.  It must be one of                                                      
> the symbols ‘ultra-heavy’, ‘heavy’ (a.k.a. ‘black’),                                                                   
> ‘ultra-bold’ (a.k.a. ‘extra-bold’), ‘bold’,                                                                            
> ‘semi-bold’ (a.k.a. ‘demi-bold’), ‘medium’, ‘normal’ (a.k.a. ‘regular’,                                                
> a.k.a. ‘book’), ‘semi-light’ (a.k.a. ‘demi-light’),                                                                    
> ‘light’, ‘extra-light’ (a.k.a. ‘ultra-light’), or ‘thin’.                                                              
    
Does `(describe-symbol 'set-face-attribute)` have the same para as above?
    
 Honestly I'm not sure on this error.

**Comment by idlip** [comment]
Maybe it is something like you don't have full fonts, or not using `:family` for setting default and fixed-pitch font?

I dont see this kinda issue anywhere.

**Comment by koss** [comment]
I have the same error. I'm using doom emacs on a mac, but I don't think that matters.

**Comment by idlip** [comment]
@koss @BonfaceKilz Do you still get the error when you clone the repo locally and load the file `haki-theme.el` ?

**Comment by idlip** [comment]
I see you there is no heavy or demi-bold in your emacs 28, yours `(describe-symbol 'set-face-attribute)` should be showing:

```emacs-lisp
from save-face-attribute docstring:
:weight

VALUE specifies the weight of the font to use.  It must be one of the
symbols ultra-bold, extra-bold, bold, semi-bold, normal,
semi-light, light, extra-light, ultra-light.
I don't see heavy here

```

I have changed heavy -\> ultra-bold 
           demi-bold -\> semi-bold

Should be solved and working as expected.

I don\'t see any mention for addition of heavy and ultra-heavy in emacs
29 (`C-h n`).

Please feel free to comment if the issue persist, or if you have any
other new one.

**Comment by idlip** [comment]
Done with this commit: b08cb7b40e2897ba865133b810ae3277c204756a

**Comment by BonfaceKilz** [comment]
Hi Dilip.

Dilip ***@***.***> aliandika:

> I see you there is no heavy or demi-bold in your emacs 28, yours `(describe-symbol 'set-face-attribute)` should be showing:
>
> ```emacs-lisp
> from save-face-attribute docstring:
> :weight
>
> VALUE specifies the weight of the font to use.  It must be one of the
> symbols ultra-bold, extra-bold, bold, semi-bold, normal,
> semi-light, light, extra-light, ultra-light.
> I don't see heavy here
>
> ```
>
This indeed makes sense:

> I have changed heavy -\> ultra-bold 
>            demi-bold -\> semi-bold
>
> Should be solved and working as expected.
>
> I don\'t see any mention for addition of heavy and ultra-heavy in emacs
> 29 (`C-h n`).

Ah yes.  Much thanks for looking into this.  I'll
try out these changes later during my work day.

-- 
(Life is like a pencil that will surely run out,
    but will leave the beautiful writing of life.)
(D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
    (hkp://keys.openpgp.org))
