### ISSUE TITLE
Fix faces for `org-agenda-schedule` and `org-agenda-deadline`

### ISSUE THREAD

**Issue by gopar** [idlip/haki#2]
You can't see the cursor when using these functions in the agenda view. Choosing a different face should be enough

**Comment by idlip** [comment]
I think it is set to foreground color only, I have set most of the unknown
faces to foreground color. I have not thought deeply on each face to notice
difference, someday I should see all face in all modes.

Will try to fix/change it very soon. Not early tho.

Thank you for bringing this into notice.

**Comment by idlip** [comment]
Have not gone deeper to understand what each org-agenda face does. But somehow added few basic lines to do that.

I don't know how it looks, just have added something.

It is surely to be improved by time.

Please lemme know if it is does not look as you needed.

Closing on this: 0de71f4bae7170e71fc7dfea59198664a5e6ecb1
