### ISSUE TITLE
Support for Centaur Tabs

### ISSUE THREAD

**Issue by gopar** [idlip/haki#3]
[Centaur Tabs ](https://github.com/ema2159/centaur-tabs)shows tab widgets on emacs buffers.
There's an issue where correct faces need to be introduce to avoid it looking like this:
![Screenshot 2023-07-15 at 3 20 13 PM](https://github.com/ema2159/centaur-tabs/assets/1545083/232e08ca-25b2-4091-bdfe-098dd489c633)

I create a ticket on their end by mistake (has the same info):
https://github.com/ema2159/centaur-tabs/issues/212

**Comment by idlip** [comment]
you should close the issue on centaurs-tab repo.

I will try to add the support for this soon. Not early tho.

For anymore missing faces or modes, you can try to see how it looks in
modus-vivendi theme and inform me in an issue (for other modes).

Thank you for showing the interest and using the theme.

**Comment by idlip** [comment]
Sorry for some delay, I have added the support for centaur-tabs.

Should be working as expected, not much tweaked tho.

Let me know if you have issue with how it looks.

**Comment by idlip** [comment]
Closing on this: aaa374e1d7b8c9283362fc7009020916c4c40975
