### ISSUE TITLE
Support for Solaire Mode

### ISSUE THREAD

**Issue by gopar** [idlip/haki#4]
Appreciate the work! Realizing that haki theme doens't play well with the following:

Solair Mode:
https://github.com/hlissner/emacs-solaire-mode

Info on adding support:
https://github.com/hlissner/emacs-solaire-mode/#theme-support-for-solaire-mode

**Comment by idlip** [comment]
Hey Gopar, Thank you for the kind words.

I have added theme faces for `solaire-mode`, but I dont know how to get it work. I have installed the package and tried to enable all modes named "solaire-*", but I dont see any difference. Even I installed `doom-theme`, slightly i can tell difference from doom-one

I might be wrong here, the purpose of the package is to differentiate bg of side windows like help,log...right?

If so, I cannot seem to get the result even after toggling modes.

Anyways, I have added the support for it, and please let me know if it appears as expected.
If not, let me know what is the unexpected looks, with screenshot please.

You can simple eval buffer from opening in eww: https://github.com/idlip/haki/raw/haki/haki-theme.el

**Comment by gopar** [comment]
Hey! Yeah the package serves  to be able to tell the difference from real files and those helper buffers (magit, help, shel/ etc)

This is a screenshot of how it looks now, mainly looking good except now the entries in the minibuffer are not readable:
<img width="1595" alt="Screenshot 2023-08-01 at 4 13 23 PM" src="https://github.com/idlip/haki/assets/1545083/09313655-f672-4ab7-be68-51f4aa43f1b1">


Using https://github.com/tumashu/vertico-posframe if that matters

**Comment by idlip** [comment]
Okay, got it working, I had to byte-compile the file.

Fixed the issue, actually changed default face to little darker one, let me know if it distinguishable, If not I will revert back to how above it looks on above image.

Also if you didnt know, you can change `haki-region` (`M-x haki-change-region`) to any color as you see it mostly everywhere.

**Comment by gopar** [comment]
Nice! Thanks! Everything seems to be working now \o/
Feel free to close :)
